(define (line x1 y1 x2 y2)
	(define start (cons x1 y1))
	(define end (cons x2 y2))
	(cons start end))
(define (start l) (car l))
(define (end l) (cdr l))
(define (xpoint p) (car p))
(define (ypoint p) (cdr p))

(define (print-point p)
	(newline)
	(display "(")
	(display (xpoint p))
	(display ",")
	(display (ypoint p))
	(display ")")
	0)
(define (mid l) 
	(define (avrg a b) (/ (+ a b) 2))
	(cons (avrg (xpoint (start l)) (xpoint (end l))) 
		(avrg (ypoint (start l)) (ypoint (end l)))))	

